//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDV_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDV_WPF.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A quantidade de um ou mais itens era negativa ou zero..
        /// </summary>
        internal static string A_QUANT_DO_ITEM_ERA_ZERO_OU_NEGATIVA {
            get {
                return ResourceManager.GetString("A_QUANT_DO_ITEM_ERA_ZERO_OU_NEGATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor à vista deve ser o último método utilizado..
        /// </summary>
        internal static string A_VISTA_DEVE_SER_O_ULTIMO_METODO {
            get {
                return ResourceManager.GetString("A_VISTA_DEVE_SER_O_ULTIMO_METODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abertura de Cupom.
        /// </summary>
        internal static string ABERTURA_DE_CUPOM {
            get {
                return ResourceManager.GetString("ABERTURA_DE_CUPOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abertura de Devolução.
        /// </summary>
        internal static string ABERTURA_DE_DEVOLUCAO {
            get {
                return ResourceManager.GetString("ABERTURA_DE_DEVOLUCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abertura de Turno.
        /// </summary>
        internal static string ABERTURA_DE_TURNO {
            get {
                return ResourceManager.GetString("ABERTURA_DE_TURNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acesso Remoto.
        /// </summary>
        internal static string ACESSO_REMOTO {
            get {
                return ResourceManager.GetString("ACESSO_REMOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AmbiPDV.
        /// </summary>
        internal static string AMBIPDV {
            get {
                return ResourceManager.GetString("AMBIPDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aplicar Desconto.
        /// </summary>
        internal static string APLICAR_DESCONTO {
            get {
                return ResourceManager.GetString("APLICAR_DESCONTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivo pode estar corrompido..
        /// </summary>
        internal static string ARQUIVO_PODE_ESTAR_CORROMPIDO {
            get {
                return ResourceManager.GetString("ARQUIVO_PODE_ESTAR_CORROMPIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O arquivo do XML foi movido após a sua gravação. Seu contador pode estar utilizando um software de backup de XML..
        /// </summary>
        internal static string ARQUIVO_XML_MOVIDO {
            get {
                return ResourceManager.GetString("ARQUIVO_XML_MOVIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Autoteste.
        /// </summary>
        internal static string AUTOTESTE {
            get {
                return ResourceManager.GetString("AUTOTESTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Autoteste concluído com sucesso..
        /// </summary>
        internal static string AUTOTESTE_CONCLUIDO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("AUTOTESTE_CONCLUIDO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O caixa encontra-se acima do limite permitido..
        /// </summary>
        internal static string CAIXA_ESTA_ACIMA_DO_LIMITE {
            get {
                return ResourceManager.GetString("CAIXA_ESTA_ACIMA_DO_LIMITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CAIXA LIVRE.
        /// </summary>
        internal static string CAIXA_LIVRE {
            get {
                return ResourceManager.GetString("CAIXA_LIVRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelamento de Venda.
        /// </summary>
        internal static string CANCELAMENTO_DE_VENDA {
            get {
                return ResourceManager.GetString("CANCELAMENTO_DE_VENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caso deixe de atualizá-la, suas vendas podem ser incorretamente tributadas..
        /// </summary>
        internal static string CASO_DEIXE_DE_ATUALIZA_LA_SUAS_VENDAS_PODEM_SER_MAL_TRIBUTADAS {
            get {
                return ResourceManager.GetString("CASO_DEIXE_DE_ATUALIZA_LA_SUAS_VENDAS_PODEM_SER_MAL_TRIBUTADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Caso esteja utilizando um serviço de backup de XML (SIEG, GestorXML, etc.), peça a seu contador para configurá-lo a fim de não remover os XMLs da pasta de origem..
        /// </summary>
        internal static string CASO_ESTEJA_USANDO_BACKUP_DE_XML {
            get {
                return ResourceManager.GetString("CASO_ESTEJA_USANDO_BACKUP_DE_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clique no botão para interromper o teste..
        /// </summary>
        internal static string CLIQUE_PARA_INTERROMPER_AUTOTESTE {
            get {
                return ResourceManager.GetString("CLIQUE_PARA_INTERROMPER_AUTOTESTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comanda.
        /// </summary>
        internal static string COMANDA {
            get {
                return ResourceManager.GetString("COMANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF/CNPJ inválido ou está em branco. Favor verificar..
        /// </summary>
        internal static string CPF_CNPJ_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_CNPJ_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CUPOM ABERTO.
        /// </summary>
        internal static string CUPOM_ABERTO {
            get {
                return ResourceManager.GetString("CUPOM_ABERTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desconto aplicado é maior que o valor do produto. Desconto removido..
        /// </summary>
        internal static string DESCONTO_APLICADO_E_MAIOR_QUE_O_VALOR {
            get {
                return ResourceManager.GetString("DESCONTO_APLICADO_E_MAIOR_QUE_O_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desconto CANCELADO para o próximo item..
        /// </summary>
        internal static string DESCONTO_CANCELADO_PARA_PROXIMO_ITEM {
            get {
                return ResourceManager.GetString("DESCONTO_CANCELADO_PARA_PROXIMO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente cancelar o último cupom fiscal lançado?.
        /// </summary>
        internal static string DESEJA_CANCELAR_CUPOM_FISCAL {
            get {
                return ResourceManager.GetString("DESEJA_CANCELAR_CUPOM_FISCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente cancelar o último cupom não fiscal lançado?.
        /// </summary>
        internal static string DESEJA_CANCELAR_CUPOM_NAO_FISCAL {
            get {
                return ResourceManager.GetString("DESEJA_CANCELAR_CUPOM_NAO_FISCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja executar o autoteste?.
        /// </summary>
        internal static string DESEJA_EXECUTAR_AUTOTESTE {
            get {
                return ResourceManager.GetString("DESEJA_EXECUTAR_AUTOTESTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja executar o fechamento do turno do funcionário?.
        /// </summary>
        internal static string DESEJA_FECHAR_O_TURNO_DO_OUTRO_FUNCIONARIO {
            get {
                return ResourceManager.GetString("DESEJA_FECHAR_O_TURNO_DO_OUTRO_FUNCIONARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Devolução de Mercadoria.
        /// </summary>
        internal static string DEVOLUCAO_DE_MERCADORIA {
            get {
                return ResourceManager.GetString("DEVOLUCAO_DE_MERCADORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para finalizar a devolução da(s) mercadoria(s), pressione F7..
        /// </summary>
        internal static string DEVOLUCAO_DEVE_SER_POR_F7 {
            get {
                return ResourceManager.GetString("DEVOLUCAO_DEVE_SER_POR_F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário fazer a configuração inicial antes de se usar o caixa..
        /// </summary>
        internal static string E_NECESSARIO_CONFIGURAR_O_CAIXA {
            get {
                return ResourceManager.GetString("E_NECESSARIO_CONFIGURAR_O_CAIXA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Havia um cupom aberto, que foi cancelado. (78).
        /// </summary>
        internal static string ECF_COM_CUPOM_ABERTO {
            get {
                return ResourceManager.GetString("ECF_COM_CUPOM_ABERTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ECF desconectada. (144).
        /// </summary>
        internal static string ECF_DESCONECTADA {
            get {
                return ResourceManager.GetString("ECF_DESCONECTADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ECF desconectada. (-6).
        /// </summary>
        internal static string ECF_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("ECF_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ECF não processa devoluções..
        /// </summary>
        internal static string ECF_NAO_PROCESSA_DEVOLUCOES {
            get {
                return ResourceManager.GetString("ECF_NAO_PROCESSA_DEVOLUCOES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ECF está sem papel. (72).
        /// </summary>
        internal static string ECF_SEM_PAPEL {
            get {
                return ResourceManager.GetString("ECF_SEM_PAPEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Efetue a redução Z com Ctrl+O..
        /// </summary>
        internal static string EFETUE_REDUCAO_Z_COM_CTRL_O {
            get {
                return ResourceManager.GetString("EFETUE_REDUCAO_Z_COM_CTRL_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entre em contato com seu contador e peça para que configurem o software de forma a não remover o XML da pasta de origem..
        /// </summary>
        internal static string ENTRE_EM_CONTATO_COM_CONTADOR {
            get {
                return ResourceManager.GetString("ENTRE_EM_CONTATO_COM_CONTADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua liçenca está próxima de expirar. Faltam {0} dias para renovar sua licença.
        ///Renove com antecedência para evitar atrasos..
        /// </summary>
        internal static string ERRO_100 {
            get {
                return ResourceManager.GetString("ERRO_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua licença expirou. Favor entrar em contato com a Trilha Informática para continuar..
        /// </summary>
        internal static string ERRO_110 {
            get {
                return ResourceManager.GetString("ERRO_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu sistema foi bloqueado..
        /// </summary>
        internal static string ERRO_205 {
            get {
                return ResourceManager.GetString("ERRO_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foi encontrada uma pendência em seu cadastro. Regularize com a Trilha Informática..
        /// </summary>
        internal static string ERRO_305 {
            get {
                return ResourceManager.GetString("ERRO_305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu serial ainda não está ativo. Peça a sua ativação com a Trilha Informática..
        /// </summary>
        internal static string ERRO_400 {
            get {
                return ResourceManager.GetString("ERRO_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Batatinha quando nasce, espalha rama pelo chão
        ///Menininha quando dorme, põe a mão no coração..
        /// </summary>
        internal static string ERRO_500 {
            get {
                return ResourceManager.GetString("ERRO_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível validar seu serial. Verifique a conexão com a Internet e tente novamente..
        /// </summary>
        internal static string ERRO_510 {
            get {
                return ResourceManager.GetString("ERRO_510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua licença não pôde ser verificada. O programa rodará por mais {0} dias antes de precisar conectar à Internet..
        /// </summary>
        internal static string ERRO_520 {
            get {
                return ResourceManager.GetString("ERRO_520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existem inconsistências em seu cadastro. Favor entrar em contato com a Trilha Informática..
        /// </summary>
        internal static string ERRO_600 {
            get {
                return ResourceManager.GetString("ERRO_600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Serial Inválido..
        /// </summary>
        internal static string ERRO_700 {
            get {
                return ResourceManager.GetString("ERRO_700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Licenciamento não pode ser confirmado..
        /// </summary>
        internal static string ERRO_999 {
            get {
                return ResourceManager.GetString("ERRO_999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao abrir novo cupom..
        /// </summary>
        internal static string ERRO_AO_ABRIR_CUPOM {
            get {
                return ResourceManager.GetString("ERRO_AO_ABRIR_CUPOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao abrir nova devolução..
        /// </summary>
        internal static string ERRO_AO_ABRIR_DEVOLUCAO {
            get {
                return ResourceManager.GetString("ERRO_AO_ABRIR_DEVOLUCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao cancelar cupom fiscal..
        /// </summary>
        internal static string ERRO_AO_CANCELAR_CUPOM_FISCAL {
            get {
                return ResourceManager.GetString("ERRO_AO_CANCELAR_CUPOM_FISCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao cancelar cupom não fiscal..
        /// </summary>
        internal static string ERRO_AO_CANCELAR_CUPOM_NAO_FISCAL {
            get {
                return ResourceManager.GetString("ERRO_AO_CANCELAR_CUPOM_NAO_FISCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao enviar a impressão do TEF para o spooler. A venda foi concluída..
        /// </summary>
        internal static string ERRO_AO_ENVIAR_IMPRESSAO_DO_TEF_PARA_SPOOLER {
            get {
                return ResourceManager.GetString("ERRO_AO_ENVIAR_IMPRESSAO_DO_TEF_PARA_SPOOLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao obter xml_de_retorno..
        /// </summary>
        internal static string ERRO_AO_OBTER_XML_DE_RETORNO {
            get {
                return ResourceManager.GetString("ERRO_AO_OBTER_XML_DE_RETORNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro durante a venda..
        /// </summary>
        internal static string ERRO_DURANTE_VENDA {
            get {
                return ResourceManager.GetString("ERRO_DURANTE_VENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro inesperado {0}.
        /// </summary>
        internal static string ERRO_INESPERADO {
            get {
                return ResourceManager.GetString("ERRO_INESPERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estoque Vazio.
        /// </summary>
        internal static string ESTOQUE_VAZIO {
            get {
                return ResourceManager.GetString("ESTOQUE_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estorno de Item.
        /// </summary>
        internal static string ESTORNO_DE_ITEM {
            get {
                return ResourceManager.GetString("ESTORNO_DE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Execute a configuração inicial antes de se usar o caixa..
        /// </summary>
        internal static string EXECUTE_A_CONFIGURACAO_INICIAL {
            get {
                return ResourceManager.GetString("EXECUTE_A_CONFIGURACAO_INICIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Se clicar em confirmar, será possível fazer vendas normalmente. 
        ///Mas se a falta de conexão persistir, por favor entre em contato com a equipe de suporte..
        /// </summary>
        internal static string EXPLICACAO_MODO_DE_CONTINGENCIA {
            get {
                return ResourceManager.GetString("EXPLICACAO_MODO_DE_CONTINGENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível abrir o programa..
        /// </summary>
        internal static string FALHA_AO_ABRIR_O_PROGRAMA {
            get {
                return ResourceManager.GetString("FALHA_AO_ABRIR_O_PROGRAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao acessar o arquivo da tabela IBPT. O aplicativo será fechado..
        /// </summary>
        internal static string FALHA_AO_ACESSAR_TABELA_IBPT {
            get {
                return ResourceManager.GetString("FALHA_AO_ACESSAR_TABELA_IBPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao carregar as configurações..
        /// </summary>
        internal static string FALHA_AO_CARREGAR_CONFIGS {
            get {
                return ResourceManager.GetString("FALHA_AO_CARREGAR_CONFIGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao estornar item..
        /// </summary>
        internal static string FALHA_AO_ESTORNAR {
            get {
                return ResourceManager.GetString("FALHA_AO_ESTORNAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FAZER SANGRIA.
        /// </summary>
        internal static string FAZER_SANGRIA {
            get {
                return ResourceManager.GetString("FAZER_SANGRIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechamento de Turno.
        /// </summary>
        internal static string FECHAMENTO_DE_TURNO {
            get {
                return ResourceManager.GetString("FECHAMENTO_DE_TURNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feche o turno do usuário atual antes..
        /// </summary>
        internal static string FECHE_O_TURNO_ANTES {
            get {
                return ResourceManager.GetString("FECHE_O_TURNO_ANTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foi encontrada uma venda pendente. Deseja continuá-la?.
        /// </summary>
        internal static string FOI_ENCONTRADA_VENDA_PENDENTE {
            get {
                return ResourceManager.GetString("FOI_ENCONTRADA_VENDA_PENDENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gravação de XML.
        /// </summary>
        internal static string GRAVACAO_DE_XML {
            get {
                return ResourceManager.GetString("GRAVACAO_DE_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificação do Consumidor.
        /// </summary>
        internal static string IDENTIFICACAO_DO_CONSUMIDOR {
            get {
                return ResourceManager.GetString("IDENTIFICACAO_DO_CONSUMIDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impossível prosseguir com a venda..
        /// </summary>
        internal static string IMPOSSIVEL_PROSSEGUIR_COM_A_VENDA {
            get {
                return ResourceManager.GetString("IMPOSSIVEL_PROSSEGUIR_COM_A_VENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impressão.
        /// </summary>
        internal static string IMPRESSAO {
            get {
                return ResourceManager.GetString("IMPRESSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impressora não configurada..
        /// </summary>
        internal static string IMPRESSORA_NAO_CONFIGURADA {
            get {
                return ResourceManager.GetString("IMPRESSORA_NAO_CONFIGURADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe sua ID para o técnico:.
        /// </summary>
        internal static string INFORME_SUA_ID {
            get {
                return ResourceManager.GetString("INFORME_SUA_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Item inválido. Verifique se o item já não foi estornado..
        /// </summary>
        internal static string ITEM_INVALIDO_VERIFIQUE {
            get {
                return ResourceManager.GetString("ITEM_INVALIDO_VERIFIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lançamento de Produto.
        /// </summary>
        internal static string LANCAMENTO_DE_PRODUTO {
            get {
                return ResourceManager.GetString("LANCAMENTO_DE_PRODUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Listando Reimpressão de Fechamento.
        /// </summary>
        internal static string LISTANDO_REIMPRESSAO_DE_FECHAMENTOS {
            get {
                return ResourceManager.GetString("LISTANDO_REIMPRESSAO_DE_FECHAMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LogErro.txt gerado..
        /// </summary>
        internal static string LOGERRO_GERADO {
            get {
                return ResourceManager.GetString("LOGERRO_GERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MODO DE DEVOLUÇÃO.
        /// </summary>
        internal static string MODO_DE_DEVOLUCAO {
            get {
                return ResourceManager.GetString("MODO_DE_DEVOLUCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não será possível fazer vendas na ECF até às 23:59:59 de hoje..
        /// </summary>
        internal static string NAO_E_POSSIVEL_VENDER_ATE_AMANHA {
            get {
                return ResourceManager.GetString("NAO_E_POSSIVEL_VENDER_ATE_AMANHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NÃO entre em contato com o Suporte Técnico antes de verificar com seu contador..
        /// </summary>
        internal static string NAO_ENTRE_EM_CONTATO_SEM_VERIFICAR_COM_CONTADOR {
            get {
                return ResourceManager.GetString("NAO_ENTRE_EM_CONTATO_SEM_VERIFICAR_COM_CONTADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível cancelar o cupom..
        /// </summary>
        internal static string NAO_FOI_POSSIVEL_CANCELAR_CUPOM {
            get {
                return ResourceManager.GetString("NAO_FOI_POSSIVEL_CANCELAR_CUPOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível imprimir o comprovante de cancelamento..
        /// </summary>
        internal static string NAO_FOI_POSSIVEL_IMPRIMIR_CANCELAMENTO {
            get {
                return ResourceManager.GetString("NAO_FOI_POSSIVEL_IMPRIMIR_CANCELAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há estoque disponível do produto selecionado..
        /// </summary>
        internal static string NAO_HA_ESTOQUE_DISPONIVEL {
            get {
                return ResourceManager.GetString("NAO_HA_ESTOQUE_DISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há serviços/produtos lançados nessa comanda..
        /// </summary>
        internal static string NAO_HA_ITEMS_LANCADOS_NA_COMANDA {
            get {
                return ResourceManager.GetString("NAO_HA_ITEMS_LANCADOS_NA_COMANDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há suporte disponível para essa situação..
        /// </summary>
        internal static string NAO_HA_SUPORTE_DISPONIVEL {
            get {
                return ResourceManager.GetString("NAO_HA_SUPORTE_DISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há turno aberto..
        /// </summary>
        internal static string NAO_HA_TURNO_ABERTO {
            get {
                return ResourceManager.GetString("NAO_HA_TURNO_ABERTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário resolução de no mínimo 1024x768. Resoluções menores não são suportadas..
        /// </summary>
        internal static string NECESSARIA_RESOLUCAO_MINIMA {
            get {
                return ResourceManager.GetString("NECESSARIA_RESOLUCAO_MINIMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É necessário fazer a redução Z antes de proceder às vendas. (88).
        /// </summary>
        internal static string NECESSARIO_FAZER_REDUCAO_Z {
            get {
                return ResourceManager.GetString("NECESSARIO_FAZER_REDUCAO_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum XML encontrado na pasta SAT/Vendas..
        /// </summary>
        internal static string NENHUM_XML_ENCONTRADO_NA_PASTA_VENDAS {
            get {
                return ResourceManager.GetString("NENHUM_XML_ENCONTRADO_NA_PASTA_VENDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obter Peso.
        /// </summary>
        internal static string OBTER_PESO {
            get {
                return ResourceManager.GetString("OBTER_PESO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação cancelada ou não concluída..
        /// </summary>
        internal static string OPERACAO_CANCELADA_OU_NAO_CONCLUIDA {
            get {
                return ResourceManager.GetString("OPERACAO_CANCELADA_OU_NAO_CONCLUIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Orçamento.
        /// </summary>
        internal static string ORCAMENTO {
            get {
                return ResourceManager.GetString("ORCAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para iniciar o programa em modo de contingência, abra-o novamente e selecione \&quot;CONFIRMAR\&quot;.
        /// </summary>
        internal static string PARA_ABRIR_EM_CONTINGENCIA_REINICIE {
            get {
                return ResourceManager.GetString("PARA_ABRIR_EM_CONTINGENCIA_REINICIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pay&amp;Go não está instalado nesse computador..
        /// </summary>
        internal static string PAYGO_NAO_ESTA_INSTALADO {
            get {
                return ResourceManager.GetString("PAYGO_NAO_ESTA_INSTALADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O PDV iniciará a checagem de conexão com o servidor e logo em seguida a atualização de registros (cadastros, vendas e fechamento de caixa). Esse procedimento pode demorar. Continuar?.
        /// </summary>
        internal static string PDV_INICIARA_ATUALIZACAO_DE_REGISTROS {
            get {
                return ResourceManager.GetString("PDV_INICIARA_ATUALIZACAO_DE_REGISTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedido.
        /// </summary>
        internal static string PEDIDO {
            get {
                return ResourceManager.GetString("PEDIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O pedido NÃO será enviado para a impressora de pedidos..
        /// </summary>
        internal static string PEDIDO_NAO_FOI_ENVIADO_PARA_IMPRESSORA {
            get {
                return ResourceManager.GetString("PEDIDO_NAO_FOI_ENVIADO_PARA_IMPRESSORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pressione \&quot;ENTER\&quot; para continuar..
        /// </summary>
        internal static string PRESSIONE_ENTER_PARA_CONTINUAR {
            get {
                return ResourceManager.GetString("PRESSIONE_ENTER_PARA_CONTINUAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pressione F12 para abrir o turno..
        /// </summary>
        internal static string PRESSIONE_F12_PARA_ABRIR_TURNO {
            get {
                return ResourceManager.GetString("PRESSIONE_F12_PARA_ABRIR_TURNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Redução Z.
        /// </summary>
        internal static string REDUCAO_Z {
            get {
                return ResourceManager.GetString("REDUCAO_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Redução Z já foi feita. (89).
        /// </summary>
        internal static string REDUCAO_Z_JA_FOI_FEITA {
            get {
                return ResourceManager.GetString("REDUCAO_Z_JA_FOI_FEITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reimpressão.
        /// </summary>
        internal static string REIMPRESSAO {
            get {
                return ResourceManager.GetString("REIMPRESSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sangria.
        /// </summary>
        internal static string SANGRIA {
            get {
                return ResourceManager.GetString("SANGRIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sangria/Suprimento.
        /// </summary>
        internal static string SANGRIA_SUPRIMENTO {
            get {
                return ResourceManager.GetString("SANGRIA_SUPRIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O SAT retornou um valor inesperado..
        /// </summary>
        internal static string SAT_RETORNOU_VALOR_INESPERADO {
            get {
                return ResourceManager.GetString("SAT_RETORNOU_VALOR_INESPERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha digitada não é válida..
        /// </summary>
        internal static string SENHA_DIGITADA_NAO_E_VALIDA {
            get {
                return ResourceManager.GetString("SENHA_DIGITADA_NAO_E_VALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Será gerado um relatório ao final da venda..
        /// </summary>
        internal static string SERA_GERADO_UM_RELATORIO {
            get {
                return ResourceManager.GetString("SERA_GERADO_UM_RELATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Servidor indisponível. Entrar em modo local?.
        /// </summary>
        internal static string SERVIDOR_INDISPONIVEL {
            get {
                return ResourceManager.GetString("SERVIDOR_INDISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Siga as instruções no TEF..
        /// </summary>
        internal static string SIGA_AS_INSTRUCOES_NO_TEF {
            get {
                return ResourceManager.GetString("SIGA_AS_INSTRUCOES_NO_TEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sincronização.
        /// </summary>
        internal static string SINCRONIZACAO {
            get {
                return ResourceManager.GetString("SINCRONIZACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O sistema está em contingência..
        /// </summary>
        internal static string SISTEMA_ESTA_EM_CONTINGENCIA {
            get {
                return ResourceManager.GetString("SISTEMA_ESTA_EM_CONTINGENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua tabela IBPT está desatualizada. Conecte-se à internet e reinicie o programa para atualizar, ou entre em contato com o suporte..
        /// </summary>
        internal static string SUA_TABELA_IBPT_ESTA_DESATUALIZADA {
            get {
                return ResourceManager.GetString("SUA_TABELA_IBPT_ESTA_DESATUALIZADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tabela IBPT.
        /// </summary>
        internal static string TABELA_IBPT {
            get {
                return ResourceManager.GetString("TABELA_IBPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tente novamente..
        /// </summary>
        internal static string TENTE_NOVAMENTE {
            get {
                return ResourceManager.GetString("TENTE_NOVAMENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tente novamente, ou use outro método de pagamento..
        /// </summary>
        internal static string TENTE_NOVAMENTE_OU_OUTRO_METODO {
            get {
                return ResourceManager.GetString("TENTE_NOVAMENTE_OU_OUTRO_METODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turno aberto com sucesso!.
        /// </summary>
        internal static string TURNO_ABERTO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("TURNO_ABERTO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Turno fechado com sucesso!.
        /// </summary>
        internal static string TURNO_FECHADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("TURNO_FECHADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Último cupom foi cancelado com sucesso..
        /// </summary>
        internal static string ULTIMO_CUPOM_FISCAL_CANCELADO {
            get {
                return ResourceManager.GetString("ULTIMO_CUPOM_FISCAL_CANCELADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Último cupom já foi cancelado..
        /// </summary>
        internal static string ULTIMO_CUPOM_JA_FOI_CANCELADO {
            get {
                return ResourceManager.GetString("ULTIMO_CUPOM_JA_FOI_CANCELADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este usuário não possui permissão para executar essa ação..
        /// </summary>
        internal static string USUARIO_NAO_POSSUI_PERMISSAO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_POSSUI_PERMISSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor à vista não pode ser menor que o valor de venda..
        /// </summary>
        internal static string VALOR_A_VISTA_NAO_PODE_SER_MENOR {
            get {
                return ResourceManager.GetString("VALOR_A_VISTA_NAO_PODE_SER_MENOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Venda.
        /// </summary>
        internal static string VENDA {
            get {
                return ResourceManager.GetString("VENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação no TEF.
        /// </summary>
        internal static string VENDA_NO_TEF {
            get {
                return ResourceManager.GetString("VENDA_NO_TEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verifique se as luzes &quot;SAT LIGADO&quot; ou &quot;PWR&quot; e &quot;SAT EM OPERAÇÃO&quot; ou &quot;OP&quot; estão ambas ligadas..
        /// </summary>
        internal static string VERIFIQUE_AS_LUZES_DO_SAT {
            get {
                return ResourceManager.GetString("VERIFIQUE_AS_LUZES_DO_SAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string VERSAO_ADENDO {
            get {
                return ResourceManager.GetString("VERSAO_ADENDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VOCÊ ESTÁ SENDO ATENDIDO POR: {0}.
        /// </summary>
        internal static string VOCE_ESTA_SENDO_ATENDIDO_POR {
            get {
                return ResourceManager.GetString("VOCE_ESTA_SENDO_ATENDIDO_POR", resourceCulture);
            }
        }
    }
}
