using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace CfeComand_0008
{
     //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class consCmd
    {

        private consCmdTpAmb tpAmbField;

        private string cUFField;

        private string xServField;

        private consCmdComando comandoField;

        private string nSegField;

        private string dhEnvioField;

        private string nserieSATField;

        private decimal versaoField;

        /// <remarks/>
        public consCmdTpAmb tpAmb
        {
            get { return this.tpAmbField; }
            set { this.tpAmbField = value; }
        }

        /// <remarks/>
        public string cUF
        {
            get { return this.cUFField; }
            set { this.cUFField = value; }
        }

        /// <remarks/>
        public string xServ
        {
            get { return this.xServField; }
            set { this.xServField = value; }
        }

        /// <remarks/>
        public consCmdComando comando
        {
            get { return this.comandoField; }
            set { this.comandoField = value; }
        }

        /// <remarks/>
        public string nSeg
        {
            get { return this.nSegField; }
            set { this.nSegField = value; }
        }

        /// <remarks/>
        public string dhEnvio
        {
            get { return this.dhEnvioField; }
            set { this.dhEnvioField = value; }
        }

        /// <remarks/>
        public string nserieSAT
        {
            get { return this.nserieSATField; }
            set { this.nserieSATField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public decimal versao
        {
            get { return this.versaoField; }
            set { this.versaoField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [XmlType(AnonymousType = true)]
    public enum consCmdTpAmb
    {

        /// <remarks/>
        [XmlEnum("1")]
        Item1,

        /// <remarks/>
        [XmlEnum("2")]
        Item2,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class consCmdComando
    {

        private string[] statusField;

        private string idCmdField;

        /// <remarks/>
        [XmlElement("status")]
        public string[] status
        {
            get { return this.statusField; }
            set { this.statusField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string idCmd
        {
            get { return this.idCmdField; }
            set { this.idCmdField = value; }
        }
    }

}