using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace CfeCancelamento_0008
{
     //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class cancCFeCFeCanc
    {

        private cancCFeCFeCancInfCFe infCFeField;

        private XmlElement anyField;

        /// <remarks/>
        public cancCFeCFeCancInfCFe infCFe
        {
            get { return this.infCFeField; }
            set { this.infCFeField = value; }
        }

        /// <remarks/>
        [XmlAnyElement()]
        public XmlElement Any
        {
            get { return this.anyField; }
            set { this.anyField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class cancCFeCFeCancInfCFe
    {

        private string dEmiField;

        private string hEmiField;

        private cancCFeCFeCancInfCFeIde ideField;

        private cancCFeCFeCancInfCFeEmit emitField;

        private cancCFeCFeCancInfCFeDest destField;

        private cancCFeCFeCancInfCFeTotal totalField;

        private cancCFeCFeCancInfCFeObsFisco[] infAdicField;

        private string versaoField;

        private string idField;

        private string chCancField;

        /// <remarks/>
        public string dEmi
        {
            get { return this.dEmiField; }
            set { this.dEmiField = value; }
        }

        /// <remarks/>
        public string hEmi
        {
            get { return this.hEmiField; }
            set { this.hEmiField = value; }
        }

        /// <remarks/>
        public cancCFeCFeCancInfCFeIde ide
        {
            get { return this.ideField; }
            set { this.ideField = value; }
        }

        /// <remarks/>
        public cancCFeCFeCancInfCFeEmit emit
        {
            get { return this.emitField; }
            set { this.emitField = value; }
        }

        /// <remarks/>
        public cancCFeCFeCancInfCFeDest dest
        {
            get { return this.destField; }
            set { this.destField = value; }
        }

        /// <remarks/>
        public cancCFeCFeCancInfCFeTotal total
        {
            get { return this.totalField; }
            set { this.totalField = value; }
        }

        /// <remarks/>
        [XmlArrayItem("obsFisco", IsNullable = false)]
        public cancCFeCFeCancInfCFeObsFisco[] infAdic
        {
            get { return this.infAdicField; }
            set { this.infAdicField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string versao
        {
            get { return this.versaoField; }
            set { this.versaoField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string chCanc
        {
            get { return this.chCancField; }
            set { this.chCancField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class cancCFeCFeCancInfCFeIde
    {

        private string cUFField;

        private string cNFField;

        private string modField;

        private string nserieSATField;

        private string nCFeField;

        private string dEmiField;

        private string hEmiField;

        private string cDVField;

        private string cNPJField;

        private string signACField;

        private string assinaturaQRCODEField;

        private string numeroCaixaField;

        /// <remarks/>
        public string cUF
        {
            get { return this.cUFField; }
            set { this.cUFField = value; }
        }

        /// <remarks/>
        public string cNF
        {
            get { return this.cNFField; }
            set { this.cNFField = value; }
        }

        /// <remarks/>
        public string mod
        {
            get { return this.modField; }
            set { this.modField = value; }
        }

        /// <remarks/>
        public string nserieSAT
        {
            get { return this.nserieSATField; }
            set { this.nserieSATField = value; }
        }

        /// <remarks/>
        public string nCFe
        {
            get { return this.nCFeField; }
            set { this.nCFeField = value; }
        }

        /// <remarks/>
        public string dEmi
        {
            get { return this.dEmiField; }
            set { this.dEmiField = value; }
        }

        /// <remarks/>
        public string hEmi
        {
            get { return this.hEmiField; }
            set { this.hEmiField = value; }
        }

        /// <remarks/>
        public string cDV
        {
            get { return this.cDVField; }
            set { this.cDVField = value; }
        }

        /// <remarks/>
        public string CNPJ
        {
            get { return this.cNPJField; }
            set { this.cNPJField = value; }
        }

        /// <remarks/>
        public string signAC
        {
            get { return this.signACField; }
            set { this.signACField = value; }
        }

        /// <remarks/>
        public string assinaturaQRCODE
        {
            get { return this.assinaturaQRCODEField; }
            set { this.assinaturaQRCODEField = value; }
        }

        /// <remarks/>
        public string numeroCaixa
        {
            get { return this.numeroCaixaField; }
            set { this.numeroCaixaField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class cancCFeCFeCancInfCFeEmit
    {

        private string cNPJField;

        private string xNomeField;

        private string xFantField;

        private cancCFeCFeCancInfCFeEmitEnderEmit enderEmitField;

        private string ieField;

        private string imField;

        /// <remarks/>
        public string CNPJ
        {
            get { return this.cNPJField; }
            set { this.cNPJField = value; }
        }

        /// <remarks/>
        public string xNome
        {
            get { return this.xNomeField; }
            set { this.xNomeField = value; }
        }

        /// <remarks/>
        public string xFant
        {
            get { return this.xFantField; }
            set { this.xFantField = value; }
        }

        /// <remarks/>
        public cancCFeCFeCancInfCFeEmitEnderEmit enderEmit
        {
            get { return this.enderEmitField; }
            set { this.enderEmitField = value; }
        }

        /// <remarks/>
        public string IE
        {
            get { return this.ieField; }
            set { this.ieField = value; }
        }

        /// <remarks/>
        public string IM
        {
            get { return this.imField; }
            set { this.imField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class cancCFeCFeCancInfCFeEmitEnderEmit
    {

        private string xLgrField;

        private string nroField;

        private string xCplField;

        private string xBairroField;

        private string xMunField;

        private string cEPField;

        /// <remarks/>
        public string xLgr
        {
            get { return this.xLgrField; }
            set { this.xLgrField = value; }
        }

        /// <remarks/>
        public string nro
        {
            get { return this.nroField; }
            set { this.nroField = value; }
        }

        /// <remarks/>
        public string xCpl
        {
            get { return this.xCplField; }
            set { this.xCplField = value; }
        }

        /// <remarks/>
        public string xBairro
        {
            get { return this.xBairroField; }
            set { this.xBairroField = value; }
        }

        /// <remarks/>
        public string xMun
        {
            get { return this.xMunField; }
            set { this.xMunField = value; }
        }

        /// <remarks/>
        public string CEP
        {
            get { return this.cEPField; }
            set { this.cEPField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class cancCFeCFeCancInfCFeDest
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [XmlElement("CNPJ", typeof(string))]
        [XmlElement("CPF", typeof(string))]
        [XmlChoiceIdentifier("ItemElementName")]
        public string Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public ItemChoiceType ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [XmlType(IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        CNPJ,

        /// <remarks/>
        CPF,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class cancCFeCFeCancInfCFeTotal
    {

        private string vCFeField;

        /// <remarks/>
        public string vCFe
        {
            get { return this.vCFeField; }
            set { this.vCFeField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class cancCFeCFeCancInfCFeObsFisco
    {

        private string xTextoField;

        private string xCampoField;

        /// <remarks/>
        public string xTexto
        {
            get { return this.xTextoField; }
            set { this.xTextoField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string xCampo
        {
            get { return this.xCampoField; }
            set { this.xCampoField = value; }
        }
    }

}