using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Xml;
using System.Xml.Serialization;

namespace CfeRecepcao_0008
{
     //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class envCFe
    {

        private string tpAmbField;

        private string idLoteField;

        private string cUFField;

        private envCFeCFe[] loteCFeField;

        private string nSegField;

        private string dhEnvioField;

        private string nserieSATField;

        private string versaoField;

        /// <remarks/>
        public string tpAmb
        {
            get { return this.tpAmbField; }
            set { this.tpAmbField = value; }
        }

        /// <remarks/>
        public string idLote
        {
            get { return this.idLoteField; }
            set { this.idLoteField = value; }
        }

        /// <remarks/>
        public string cUF
        {
            get { return this.cUFField; }
            set { this.cUFField = value; }
        }

        /// <remarks/>
        [XmlArrayItem("CFe", IsNullable = false)]
        public envCFeCFe[] LoteCFe
        {
            get { return this.loteCFeField; }
            set { this.loteCFeField = value; }
        }

        /// <remarks/>
        public string nSeg
        {
            get { return this.nSegField; }
            set { this.nSegField = value; }
        }

        /// <remarks/>
        public string dhEnvio
        {
            get { return this.dhEnvioField; }
            set { this.dhEnvioField = value; }
        }

        /// <remarks/>
        public string nserieSAT
        {
            get { return this.nserieSATField; }
            set { this.nserieSATField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string versao
        {
            get { return this.versaoField; }
            set { this.versaoField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFe
    {

        private envCFeCFeInfCFe infCFeField;

        private XmlElement anyField;

        /// <remarks/>
        public envCFeCFeInfCFe infCFe
        {
            get { return this.infCFeField; }
            set { this.infCFeField = value; }
        }

        /// <remarks/>
        [XmlAnyElement()]
        public XmlElement Any
        {
            get { return this.anyField; }
            set { this.anyField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFe
    {

        private envCFeCFeInfCFeIde ideField;

        private envCFeCFeInfCFeEmit emitField;

        private envCFeCFeInfCFeDest destField;

        private envCFeCFeInfCFeEntrega entregaField;

        private envCFeCFeInfCFeDet[] detField;

        private envCFeCFeInfCFeTotal totalField;

        private envCFeCFeInfCFePgto pgtoField;

        private envCFeCFeInfCFeInfAdic infAdicField;

        private envCFeCFeInfCFeObsFisco[] obsFiscoField;

        private string versaoField;

        private string versaoDadosEntField;

        private string versaoSBField;

        private string idField;

        /// <remarks/>
        public envCFeCFeInfCFeIde ide
        {
            get { return this.ideField; }
            set { this.ideField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeEmit emit
        {
            get { return this.emitField; }
            set { this.emitField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeDest dest
        {
            get { return this.destField; }
            set { this.destField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeEntrega entrega
        {
            get { return this.entregaField; }
            set { this.entregaField = value; }
        }

        /// <remarks/>
        [XmlElement("det")]
        public envCFeCFeInfCFeDet[] det
        {
            get { return this.detField; }
            set { this.detField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeTotal total
        {
            get { return this.totalField; }
            set { this.totalField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFePgto pgto
        {
            get { return this.pgtoField; }
            set { this.pgtoField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeInfAdic infAdic
        {
            get { return this.infAdicField; }
            set { this.infAdicField = value; }
        }

        /// <remarks/>
        [XmlElement("obsFisco")]
        public envCFeCFeInfCFeObsFisco[] obsFisco
        {
            get { return this.obsFiscoField; }
            set { this.obsFiscoField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string versao
        {
            get { return this.versaoField; }
            set { this.versaoField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string versaoDadosEnt
        {
            get { return this.versaoDadosEntField; }
            set { this.versaoDadosEntField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string versaoSB
        {
            get { return this.versaoSBField; }
            set { this.versaoSBField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeIde
    {

        private string cUFField;

        private string cNFField;

        private string modField;

        private string nserieSATField;

        private string nCFeField;

        private string dEmiField;

        private string hEmiField;

        private string cDVField;

        private string tpAmbField;

        private string cNPJField;

        private string signACField;

        private string assinaturaQRCODEField;

        private string numeroCaixaField;

        /// <remarks/>
        public string cUF
        {
            get { return this.cUFField; }
            set { this.cUFField = value; }
        }

        /// <remarks/>
        public string cNF
        {
            get { return this.cNFField; }
            set { this.cNFField = value; }
        }

        /// <remarks/>
        public string mod
        {
            get { return this.modField; }
            set { this.modField = value; }
        }

        /// <remarks/>
        public string nserieSAT
        {
            get { return this.nserieSATField; }
            set { this.nserieSATField = value; }
        }

        /// <remarks/>
        public string nCFe
        {
            get { return this.nCFeField; }
            set { this.nCFeField = value; }
        }

        /// <remarks/>
        public string dEmi
        {
            get { return this.dEmiField; }
            set { this.dEmiField = value; }
        }

        /// <remarks/>
        public string hEmi
        {
            get { return this.hEmiField; }
            set { this.hEmiField = value; }
        }

        /// <remarks/>
        public string cDV
        {
            get { return this.cDVField; }
            set { this.cDVField = value; }
        }

        /// <remarks/>
        public string tpAmb
        {
            get { return this.tpAmbField; }
            set { this.tpAmbField = value; }
        }

        /// <remarks/>
        public string CNPJ
        {
            get { return this.cNPJField; }
            set { this.cNPJField = value; }
        }

        /// <remarks/>
        public string signAC
        {
            get { return this.signACField; }
            set { this.signACField = value; }
        }

        /// <remarks/>
        public string assinaturaQRCODE
        {
            get { return this.assinaturaQRCODEField; }
            set { this.assinaturaQRCODEField = value; }
        }

        /// <remarks/>
        public string numeroCaixa
        {
            get { return this.numeroCaixaField; }
            set { this.numeroCaixaField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeEmit
    {

        private string cNPJField;

        private string xNomeField;

        private string xFantField;

        private envCFeCFeInfCFeEmitEnderEmit enderEmitField;

        private string ieField;

        private string imField;

        private string cRegTribField;

        private string cRegTribISSQNField;

        private string indRatISSQNField;

        /// <remarks/>
        public string CNPJ
        {
            get { return this.cNPJField; }
            set { this.cNPJField = value; }
        }

        /// <remarks/>
        public string xNome
        {
            get { return this.xNomeField; }
            set { this.xNomeField = value; }
        }

        /// <remarks/>
        public string xFant
        {
            get { return this.xFantField; }
            set { this.xFantField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeEmitEnderEmit enderEmit
        {
            get { return this.enderEmitField; }
            set { this.enderEmitField = value; }
        }

        /// <remarks/>
        public string IE
        {
            get { return this.ieField; }
            set { this.ieField = value; }
        }

        /// <remarks/>
        public string IM
        {
            get { return this.imField; }
            set { this.imField = value; }
        }

        /// <remarks/>
        public string cRegTrib
        {
            get { return this.cRegTribField; }
            set { this.cRegTribField = value; }
        }

        /// <remarks/>
        public string cRegTribISSQN
        {
            get { return this.cRegTribISSQNField; }
            set { this.cRegTribISSQNField = value; }
        }

        /// <remarks/>
        public string indRatISSQN
        {
            get { return this.indRatISSQNField; }
            set { this.indRatISSQNField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeEmitEnderEmit
    {

        private string xLgrField;

        private string nroField;

        private string xCplField;

        private string xBairroField;

        private string xMunField;

        private string cEPField;

        /// <remarks/>
        public string xLgr
        {
            get { return this.xLgrField; }
            set { this.xLgrField = value; }
        }

        /// <remarks/>
        public string nro
        {
            get { return this.nroField; }
            set { this.nroField = value; }
        }

        /// <remarks/>
        public string xCpl
        {
            get { return this.xCplField; }
            set { this.xCplField = value; }
        }

        /// <remarks/>
        public string xBairro
        {
            get { return this.xBairroField; }
            set { this.xBairroField = value; }
        }

        /// <remarks/>
        public string xMun
        {
            get { return this.xMunField; }
            set { this.xMunField = value; }
        }

        /// <remarks/>
        public string CEP
        {
            get { return this.cEPField; }
            set { this.cEPField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDest
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        private string xNomeField;

        /// <remarks/>
        [XmlElement("CNPJ", typeof(string))]
        [XmlElement("CPF", typeof(string))]
        [XmlChoiceIdentifier("ItemElementName")]
        public string Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public ItemChoiceType ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }

        /// <remarks/>
        public string xNome
        {
            get { return this.xNomeField; }
            set { this.xNomeField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [XmlType(IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <summary>
        /// Caso a informação digitada tenha sido um CNPJ.
        /// </summary>
        CNPJ,

        /// <summary>
        /// Caso a informação digitada tenha sido um CPF.
        /// </summary>
        CPF,

        /// <summary>
        /// Caso nenhuma informação tenha sido digitada.
        /// </summary>
        NENHUM,

        /// <summary>
        /// Caso não seja uma venda fiscal.
        /// </summary>
        DEMONSTRACAO,

        /// <summary>
        /// O sistema não está em modo de venda.
        /// </summary>
        FECHADO,

        /// <summary>
        /// O cupom foi aberto, porém não foi identificado ainda.
        /// </summary>
        ABERTO,

        ///// <summary>
        ///// O sistema se encontra em modo de devolução.
        ///// </summary>
        //DEVOLUCAO
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeEntrega
    {

        private string xLgrField;

        private string nroField;

        private string xCplField;

        private string xBairroField;

        private string xMunField;

        private string ufField;

        /// <remarks/>
        public string xLgr
        {
            get { return this.xLgrField; }
            set { this.xLgrField = value; }
        }

        /// <remarks/>
        public string nro
        {
            get { return this.nroField; }
            set { this.nroField = value; }
        }

        /// <remarks/>
        public string xCpl
        {
            get { return this.xCplField; }
            set { this.xCplField = value; }
        }

        /// <remarks/>
        public string xBairro
        {
            get { return this.xBairroField; }
            set { this.xBairroField = value; }
        }

        /// <remarks/>
        public string xMun
        {
            get { return this.xMunField; }
            set { this.xMunField = value; }
        }

        /// <remarks/>
        public string UF
        {
            get { return this.ufField; }
            set { this.ufField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDet
    {

        private envCFeCFeInfCFeDetProd prodField;

        private envCFeCFeInfCFeDetImposto impostoField;

        private string infAdProdField;

        private string nItemField;

        [XmlIgnoreAttribute()] public string familia;
        [XmlIgnoreAttribute()] public int? idScannTech;

        [XmlIgnoreAttribute()] public bool scannTech => idScannTech is not null;
        [XmlIgnoreAttribute()] public bool kit = false;
        [XmlIgnoreAttribute()] public bool atacado = false;
        [XmlIgnoreAttribute()] public decimal descAtacado;

        /// <remarks/>
        public envCFeCFeInfCFeDetProd prod
        {
            get { return this.prodField; }
            set { this.prodField = value; }
        }
        [XmlIgnoreAttribute()]
        public decimal QuantDec 
        {
            get => decimal.Parse(prod.qCom);
            set => prod.qCom = value.ToString("N3");
        }

        /// <remarks/>
        public envCFeCFeInfCFeDetImposto imposto
        {
            get { return this.impostoField; }
            set { this.impostoField = value; }
        }

        /// <remarks/>
        public string infAdProd
        {
            get { return this.infAdProdField; }
            set { this.infAdProdField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string nItem
        {
            get { return this.nItemField; }
            set { this.nItemField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetProd
    {

        private string cProdField;

        private string cEANField;

        private string xProdField;

        private string nCMField;

        private string cESTField;

        private string cFOPField;

        private string uComField;

        private string qComField;

        private string vUnComField;

        private string vProdField;

        private string indRegraField;

        private string vDescField;

        private string vOutroField;

        private string vItemField;

        private string vRatDescField;

        private string vRatAcrField;

        private envCFeCFeInfCFeDetProdObsFiscoDet[] obsFiscoDetField;
        [XmlIgnoreAttribute()]
        public string vUnComOri;

        /// <remarks/>
        public string cProd
        {
            get { return this.cProdField; }
            set { this.cProdField = value; }
        }

        /// <remarks/>
        public string cEAN
        {
            get { return this.cEANField; }
            set { this.cEANField = value; }
        }

        /// <remarks/>
        public string xProd
        {
            get { return this.xProdField; }
            set { this.xProdField = value; }
        }

        /// <remarks/>
        public string NCM
        {
            get { return this.nCMField; }
            set { this.nCMField = value; }
        }

        /// <remarks/>
        public string CEST
        {
            get { return this.cESTField; }
            set { this.cESTField = value; }
        }

        /// <remarks/>
        public string CFOP
        {
            get { return this.cFOPField; }
            set { this.cFOPField = value; }
        }

        /// <remarks/>
        public string uCom
        {
            get { return this.uComField; }
            set { this.uComField = value; }
        }

        /// <remarks/>
        public string qCom
        {
            get { return this.qComField; }
            set { this.qComField = value; }
        }

        /// <remarks/>
        public string vUnCom
        {
            get { return this.vUnComField; }
            set { this.vUnComField = value; }
        }

        /// <remarks/>
        public string vProd
        {
            get { return this.vProdField; }
            set { this.vProdField = value; }
        }

        /// <remarks/>
        public string indRegra
        {
            get { return this.indRegraField; }
            set { this.indRegraField = value; }
        }

        /// <remarks/>
        public string vDesc
        {
            get { return this.vDescField; }
            set { this.vDescField = value; }
        }

        /// <remarks/>
        public string vOutro
        {
            get { return this.vOutroField; }
            set { this.vOutroField = value; }
        }

        /// <remarks/>
        public string vItem
        {
            get { return this.vItemField; }
            set { this.vItemField = value; }
        }

        /// <remarks/>
        public string vRatDesc
        {
            get { return this.vRatDescField; }
            set { this.vRatDescField = value; }
        }

        /// <remarks/>
        public string vRatAcr
        {
            get { return this.vRatAcrField; }
            set { this.vRatAcrField = value; }
        }

        /// <remarks/>
        [XmlElement("obsFiscoDet")]
        public envCFeCFeInfCFeDetProdObsFiscoDet[] obsFiscoDet
        {
            get { return this.obsFiscoDetField; }
            set { this.obsFiscoDetField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetProdObsFiscoDet
    {

        private string xTextoDetField;

        private string xCampoDetField;

        /// <remarks/>
        public string xTextoDet
        {
            get { return this.xTextoDetField; }
            set { this.xTextoDetField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string xCampoDet
        {
            get { return this.xCampoDetField; }
            set { this.xCampoDetField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImposto
    {

        private string vItem12741Field;

        private object itemField;

        private envCFeCFeInfCFeDetImpostoPIS pISField;

        private envCFeCFeInfCFeDetImpostoPISST pISSTField;

        private envCFeCFeInfCFeDetImpostoCOFINS cOFINSField;

        private envCFeCFeInfCFeDetImpostoCOFINSST cOFINSSTField;
        private string CSTField;

        /// <remarks/>
        public string vItem12741
        {
            get { return this.vItem12741Field; }
            set { this.vItem12741Field = value; }
        }

        /// <remarks/>
        [XmlElement("ICMS", typeof(envCFeCFeInfCFeDetImpostoICMS))]
        [XmlElement("ISSQN", typeof(envCFeCFeInfCFeDetImpostoISSQN))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeDetImpostoPIS PIS
        {
            get { return this.pISField; }
            set { this.pISField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeDetImpostoPISST PISST
        {
            get { return this.pISSTField; }
            set { this.pISSTField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeDetImpostoCOFINS COFINS
        {
            get { return this.cOFINSField; }
            set { this.cOFINSField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeDetImpostoCOFINSST COFINSST
        {
            get { return this.cOFINSSTField; }
            set { this.cOFINSSTField = value; }
        }

        public string CST
        {
            get => CSTField;
            set => CSTField = value;
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoICMS
    {

        private object itemField;

        /// <remarks/>
        [XmlElement("ICMS00", typeof(envCFeCFeInfCFeDetImpostoICMSICMS00))]
        [XmlElement("ICMS40", typeof(envCFeCFeInfCFeDetImpostoICMSICMS40))]
        [XmlElement("ICMSSN102", typeof(envCFeCFeInfCFeDetImpostoICMSICMSSN102))]
        [XmlElement("ICMSSN900", typeof(envCFeCFeInfCFeDetImpostoICMSICMSSN900))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoICMSICMS00
    {

        private string origField;

        private string cSTField;

        private string pICMSField;

        private string vICMSField;

        /// <remarks/>
        public string Orig
        {
            get { return this.origField; }
            set { this.origField = value; }
        }

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }

        /// <remarks/>
        public string pICMS
        {
            get { return this.pICMSField; }
            set { this.pICMSField = value; }
        }

        /// <remarks/>
        public string vICMS
        {
            get { return this.vICMSField; }
            set { this.vICMSField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoICMSICMS40
    {

        private string origField;

        private string cSTField;

        /// <remarks/>
        public string Orig
        {
            get { return this.origField; }
            set { this.origField = value; }
        }

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoICMSICMSSN102
    {

        private string origField;

        private string cSOSNField;

        /// <remarks/>
        public string Orig
        {
            get { return this.origField; }
            set { this.origField = value; }
        }

        /// <remarks/>
        public string CSOSN
        {
            get { return this.cSOSNField; }
            set { this.cSOSNField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoICMSICMSSN900
    {

        private string origField;

        private string cSOSNField;

        private string pICMSField;

        private string vICMSField;

        /// <remarks/>
        public string Orig
        {
            get { return this.origField; }
            set { this.origField = value; }
        }

        /// <remarks/>
        public string CSOSN
        {
            get { return this.cSOSNField; }
            set { this.cSOSNField = value; }
        }

        /// <remarks/>
        public string pICMS
        {
            get { return this.pICMSField; }
            set { this.pICMSField = value; }
        }

        /// <remarks/>
        public string vICMS
        {
            get { return this.vICMSField; }
            set { this.vICMSField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoISSQN
    {

        private string vDeducISSQNField;

        private string vBCField;

        private string vAliqField;

        private string vISSQNField;

        private string cMunFGField;

        private string cListServField;

        private string cServTribMunField;

        private string cNatOpField;

        private string indIncFiscField;

        /// <remarks/>
        public string vDeducISSQN
        {
            get { return this.vDeducISSQNField; }
            set { this.vDeducISSQNField = value; }
        }

        /// <remarks/>
        public string vBC
        {
            get { return this.vBCField; }
            set { this.vBCField = value; }
        }

        /// <remarks/>
        public string vAliq
        {
            get { return this.vAliqField; }
            set { this.vAliqField = value; }
        }

        /// <remarks/>
        public string vISSQN
        {
            get { return this.vISSQNField; }
            set { this.vISSQNField = value; }
        }

        /// <remarks/>
        public string cMunFG
        {
            get { return this.cMunFGField; }
            set { this.cMunFGField = value; }
        }

        /// <remarks/>
        public string cListServ
        {
            get { return this.cListServField; }
            set { this.cListServField = value; }
        }

        /// <remarks/>
        public string cServTribMun
        {
            get { return this.cServTribMunField; }
            set { this.cServTribMunField = value; }
        }

        /// <remarks/>
        public string cNatOp
        {
            get { return this.cNatOpField; }
            set { this.cNatOpField = value; }
        }

        /// <remarks/>
        public string indIncFisc
        {
            get { return this.indIncFiscField; }
            set { this.indIncFiscField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoPIS
    {

        private object itemField;

        /// <remarks/>
        [XmlElement("PISAliq", typeof(envCFeCFeInfCFeDetImpostoPISPISAliq))]
        [XmlElement("PISNT", typeof(envCFeCFeInfCFeDetImpostoPISPISNT))]
        [XmlElement("PISOutr", typeof(envCFeCFeInfCFeDetImpostoPISPISOutr))]
        [XmlElement("PISQtde", typeof(envCFeCFeInfCFeDetImpostoPISPISQtde))]
        [XmlElement("PISSN", typeof(envCFeCFeInfCFeDetImpostoPISPISSN))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoPISPISAliq
    {

        private string cSTField;

        private string vBCField;

        private string pPISField;

        private string vPISField;

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }

        /// <remarks/>
        public string vBC
        {
            get { return this.vBCField; }
            set { this.vBCField = value; }
        }

        /// <remarks/>
        public string pPIS
        {
            get { return this.pPISField; }
            set { this.pPISField = value; }
        }

        /// <remarks/>
        public string vPIS
        {
            get { return this.vPISField; }
            set { this.vPISField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoPISPISNT
    {

        private string cSTField;

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoPISPISOutr
    {

        private string cSTField;

        private string[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private string vPISField;

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }

        /// <remarks/>
        [XmlElement("pPIS", typeof(string))]
        [XmlElement("qBCProd", typeof(string))]
        [XmlElement("vAliqProd", typeof(string))]
        [XmlElement("vBC", typeof(string))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public string[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }

        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType[] ItemsElementName
        {
            get { return this.itemsElementNameField; }
            set { this.itemsElementNameField = value; }
        }

        /// <remarks/>
        public string vPIS
        {
            get { return this.vPISField; }
            set { this.vPISField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [XmlType(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        pPIS,

        /// <remarks/>
        qBCProd,

        /// <remarks/>
        vAliqProd,

        /// <remarks/>
        vBC,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoPISPISQtde
    {

        private string cSTField;

        private string qBCProdField;

        private string vAliqProdField;

        private string vPISField;

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }

        /// <remarks/>
        public string qBCProd
        {
            get { return this.qBCProdField; }
            set { this.qBCProdField = value; }
        }

        /// <remarks/>
        public string vAliqProd
        {
            get { return this.vAliqProdField; }
            set { this.vAliqProdField = value; }
        }

        /// <remarks/>
        public string vPIS
        {
            get { return this.vPISField; }
            set { this.vPISField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoPISPISSN
    {

        private string cSTField;

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoPISST
    {

        private string[] itemsField;

        private ItemsChoiceType1[] itemsElementNameField;

        private string vPISField;

        /// <remarks/>
        [XmlElement("pPIS", typeof(string))]
        [XmlElement("qBCProd", typeof(string))]
        [XmlElement("vAliqProd", typeof(string))]
        [XmlElement("vBC", typeof(string))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public string[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }

        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType1[] ItemsElementName
        {
            get { return this.itemsElementNameField; }
            set { this.itemsElementNameField = value; }
        }

        /// <remarks/>
        public string vPIS
        {
            get { return this.vPISField; }
            set { this.vPISField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [XmlType(IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {

        /// <remarks/>
        pPIS,

        /// <remarks/>
        qBCProd,

        /// <remarks/>
        vAliqProd,

        /// <remarks/>
        vBC,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoCOFINS
    {

        private object itemField;

        /// <remarks/>
        [XmlElement("COFINSAliq", typeof(envCFeCFeInfCFeDetImpostoCOFINSCOFINSAliq))]
        [XmlElement("COFINSNT", typeof(envCFeCFeInfCFeDetImpostoCOFINSCOFINSNT))]
        [XmlElement("COFINSOutr", typeof(envCFeCFeInfCFeDetImpostoCOFINSCOFINSOutr))]
        [XmlElement("COFINSQtde", typeof(envCFeCFeInfCFeDetImpostoCOFINSCOFINSQtde))]
        [XmlElement("COFINSSN", typeof(envCFeCFeInfCFeDetImpostoCOFINSCOFINSSN))]
        public object Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoCOFINSCOFINSAliq
    {

        private string cSTField;

        private string vBCField;

        private string pCOFINSField;

        private string vCOFINSField;

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }

        /// <remarks/>
        public string vBC
        {
            get { return this.vBCField; }
            set { this.vBCField = value; }
        }

        /// <remarks/>
        public string pCOFINS
        {
            get { return this.pCOFINSField; }
            set { this.pCOFINSField = value; }
        }

        /// <remarks/>
        public string vCOFINS
        {
            get { return this.vCOFINSField; }
            set { this.vCOFINSField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoCOFINSCOFINSNT
    {

        private string cSTField;

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoCOFINSCOFINSOutr
    {

        private string cSTField;

        private string[] itemsField;

        private ItemsChoiceType2[] itemsElementNameField;

        private string vCOFINSField;

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }

        /// <remarks/>
        [XmlElement("pCOFINS", typeof(string))]
        [XmlElement("qBCProd", typeof(string))]
        [XmlElement("vAliqProd", typeof(string))]
        [XmlElement("vBC", typeof(string))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public string[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }

        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType2[] ItemsElementName
        {
            get { return this.itemsElementNameField; }
            set { this.itemsElementNameField = value; }
        }

        /// <remarks/>
        public string vCOFINS
        {
            get { return this.vCOFINSField; }
            set { this.vCOFINSField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [XmlType(IncludeInSchema = false)]
    public enum ItemsChoiceType2
    {

        /// <remarks/>
        pCOFINS,

        /// <remarks/>
        qBCProd,

        /// <remarks/>
        vAliqProd,

        /// <remarks/>
        vBC,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoCOFINSCOFINSQtde
    {

        private string cSTField;

        private string qBCProdField;

        private string vAliqProdField;

        private string vCOFINSField;

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }

        /// <remarks/>
        public string qBCProd
        {
            get { return this.qBCProdField; }
            set { this.qBCProdField = value; }
        }

        /// <remarks/>
        public string vAliqProd
        {
            get { return this.vAliqProdField; }
            set { this.vAliqProdField = value; }
        }

        /// <remarks/>
        public string vCOFINS
        {
            get { return this.vCOFINSField; }
            set { this.vCOFINSField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoCOFINSCOFINSSN
    {

        private string cSTField;

        /// <remarks/>
        public string CST
        {
            get { return this.cSTField; }
            set { this.cSTField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeDetImpostoCOFINSST
    {

        private string[] itemsField;

        private ItemsChoiceType3[] itemsElementNameField;

        private string vCOFINSField;

        /// <remarks/>
        [XmlElement("pCOFINS", typeof(string))]
        [XmlElement("qBCProd", typeof(string))]
        [XmlElement("vAliqProd", typeof(string))]
        [XmlElement("vBC", typeof(string))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public string[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }

        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType3[] ItemsElementName
        {
            get { return this.itemsElementNameField; }
            set { this.itemsElementNameField = value; }
        }

        /// <remarks/>
        public string vCOFINS
        {
            get { return this.vCOFINSField; }
            set { this.vCOFINSField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [XmlType(IncludeInSchema = false)]
    public enum ItemsChoiceType3
    {

        /// <remarks/>
        pCOFINS,

        /// <remarks/>
        qBCProd,

        /// <remarks/>
        vAliqProd,

        /// <remarks/>
        vBC,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeTotal
    {

        private envCFeCFeInfCFeTotalICMSTot iCMSTotField;

        private string vCFeField;

        private envCFeCFeInfCFeTotalISSQNtot iSSQNtotField;

        private envCFeCFeInfCFeTotalDescAcrEntr descAcrEntrField;

        private string vCFeLei12741Field;

        /// <remarks/>
        public envCFeCFeInfCFeTotalICMSTot ICMSTot
        {
            get { return this.iCMSTotField; }
            set { this.iCMSTotField = value; }
        }

        /// <remarks/>
        public string vCFe
        {
            get { return this.vCFeField; }
            set { this.vCFeField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeTotalISSQNtot ISSQNtot
        {
            get { return this.iSSQNtotField; }
            set { this.iSSQNtotField = value; }
        }

        /// <remarks/>
        public envCFeCFeInfCFeTotalDescAcrEntr DescAcrEntr
        {
            get { return this.descAcrEntrField; }
            set { this.descAcrEntrField = value; }
        }

        /// <remarks/>
        public string vCFeLei12741
        {
            get { return this.vCFeLei12741Field; }
            set { this.vCFeLei12741Field = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeTotalICMSTot
    {

        private string vICMSField;

        private string vProdField;

        private string vDescField;

        private string vPISField;

        private string vCOFINSField;

        private string vPISSTField;

        private string vCOFINSSTField;

        private string vOutroField;

        /// <remarks/>
        public string vICMS
        {
            get { return this.vICMSField; }
            set { this.vICMSField = value; }
        }

        /// <remarks/>
        public string vProd
        {
            get { return this.vProdField; }
            set { this.vProdField = value; }
        }

        /// <remarks/>
        public string vDesc
        {
            get { return this.vDescField; }
            set { this.vDescField = value; }
        }

        /// <remarks/>
        public string vPIS
        {
            get { return this.vPISField; }
            set { this.vPISField = value; }
        }

        /// <remarks/>
        public string vCOFINS
        {
            get { return this.vCOFINSField; }
            set { this.vCOFINSField = value; }
        }

        /// <remarks/>
        public string vPISST
        {
            get { return this.vPISSTField; }
            set { this.vPISSTField = value; }
        }

        /// <remarks/>
        public string vCOFINSST
        {
            get { return this.vCOFINSSTField; }
            set { this.vCOFINSSTField = value; }
        }

        /// <remarks/>
        public string vOutro
        {
            get { return this.vOutroField; }
            set { this.vOutroField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeTotalISSQNtot
    {

        private string vBCField;

        private string vISSField;

        private string vPISField;

        private string vCOFINSField;

        private string vPISSTField;

        private string vCOFINSSTField;

        /// <remarks/>
        public string vBC
        {
            get { return this.vBCField; }
            set { this.vBCField = value; }
        }

        /// <remarks/>
        public string vISS
        {
            get { return this.vISSField; }
            set { this.vISSField = value; }
        }

        /// <remarks/>
        public string vPIS
        {
            get { return this.vPISField; }
            set { this.vPISField = value; }
        }

        /// <remarks/>
        public string vCOFINS
        {
            get { return this.vCOFINSField; }
            set { this.vCOFINSField = value; }
        }

        /// <remarks/>
        public string vPISST
        {
            get { return this.vPISSTField; }
            set { this.vPISSTField = value; }
        }

        /// <remarks/>
        public string vCOFINSST
        {
            get { return this.vCOFINSSTField; }
            set { this.vCOFINSSTField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeTotalDescAcrEntr
    {

        private string itemField;

        private ItemChoiceType1 itemElementNameField;

        /// <remarks/>
        [XmlElement("vAcresSubtot", typeof(string))]
        [XmlElement("vDescSubtot", typeof(string))]
        [XmlChoiceIdentifier("ItemElementName")]
        public string Item
        {
            get { return this.itemField; }
            set { this.itemField = value; }
        }

        /// <remarks/>
        [XmlIgnore()]
        public ItemChoiceType1 ItemElementName
        {
            get { return this.itemElementNameField; }
            set { this.itemElementNameField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [XmlType(IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        vAcresSubtot,

        /// <remarks/>
        vDescSubtot,
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFePgto
    {

        private envCFeCFeInfCFePgtoMP[] mpField;

        private string vTrocoField;
        private decimal dTrocoField;

        /// <remarks/>
        [XmlElement("MP")]
        public envCFeCFeInfCFePgtoMP[] MP
        {
            get { return this.mpField; }
            set { this.mpField = value; }
        }

        /// <remarks/>
        public string vTroco
        {
            get { return this.vTrocoField; }
            set { this.vTrocoField = value; }
        }

        [XmlIgnore]
        public decimal dTroco
        {
            get => dTrocoField;
            set => dTrocoField = value;
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFePgtoMP
    {

        private string cMPField;

        private string vMPField;

        private string cAdmCField;
        private int idClienteField;
        private DateTime vencimentoField;
        private bool descontoField;
        private decimal dec_vMPField;

        /// <remarks/>
        public string cMP
        {
            get { return this.cMPField; }
            set { this.cMPField = value; }
        }

        /// <remarks/>
        public string vMP
        {
            get { return this.vMPField; }
            set { this.vMPField = value; }
        }

        /// <remarks/>
        public string cAdmC
        {
            get { return this.cAdmCField; }
            set { this.cAdmCField = value; }
        }
        [XmlIgnore]
        public int idCliente
        {
            get => idClienteField;
            set => idClienteField = value;
        }

        [XmlIgnore]
        public DateTime vencimento
        {
            get => vencimentoField;
            set => vencimentoField = value;
        }

        [XmlIgnore]
        public bool desconto
        {
            get => descontoField;
            set => descontoField = value;
        }

        [XmlIgnore]
        public decimal dec_vMP
        {
            get => dec_vMPField;
            set => dec_vMPField = value;
        }
        [XmlIgnore]
        public int idADMINS { get; set; }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeInfAdic
    {

        private string infCplField;

        /// <remarks/>
        public string infCpl
        {
            get { return this.infCplField; }
            set { this.infCplField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class envCFeCFeInfCFeObsFisco
    {

        private string xTextoField;

        private string xCampoField;

        /// <remarks/>
        public string xTexto
        {
            get { return this.xTextoField; }
            set { this.xTextoField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string xCampo
        {
            get { return this.xCampoField; }
            set { this.xCampoField = value; }
        }
    }
}