using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace CfeStatus_0008
{
     //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public partial class consStat
    {

        private string tpAmbField;

        private string cUFField;

        private string xServField;

        private string nSegField;

        private string dhEnvioField;

        private string nserieSATField;

        private consStatStatus statusField;

        private string versaoField;

        /// <remarks/>
        public string tpAmb
        {
            get { return this.tpAmbField; }
            set { this.tpAmbField = value; }
        }

        /// <remarks/>
        public string cUF
        {
            get { return this.cUFField; }
            set { this.cUFField = value; }
        }

        /// <remarks/>
        public string xServ
        {
            get { return this.xServField; }
            set { this.xServField = value; }
        }

        /// <remarks/>
        public string nSeg
        {
            get { return this.nSegField; }
            set { this.nSegField = value; }
        }

        /// <remarks/>
        public string dhEnvio
        {
            get { return this.dhEnvioField; }
            set { this.dhEnvioField = value; }
        }

        /// <remarks/>
        public string nserieSAT
        {
            get { return this.nserieSATField; }
            set { this.nserieSATField = value; }
        }

        /// <remarks/>
        public consStatStatus status
        {
            get { return this.statusField; }
            set { this.statusField = value; }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string versao
        {
            get { return this.versaoField; }
            set { this.versaoField = value; }
        }
    }

    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public partial class consStatStatus
    {

        private string tipoLanField;

        private string lanIPField;

        private string lanMACField;

        private string lanMASKField;

        private string lanGWField;

        private string lanDNS1Field;

        private string lanDNS2Field;

        private string statLanField;

        private string nBatField;

        private string mtTotalField;

        private string mtUsadaField;

        private string datahoraField;

        private string verSoftField;

        private string verLayField;

        private string ultimoCFeField;

        private string listaInicialField;

        private string listafinalField;

        private string dhTransmissaoField;

        private string dhComunicacaoField;

        private string cERT_EMISSAOField;

        private string cERT_VENCIMENTOField;

        private string eSTADO_OPERACAOField;

        /// <remarks/>
        public string tipoLan
        {
            get { return this.tipoLanField; }
            set { this.tipoLanField = value; }
        }

        /// <remarks/>
        public string lanIP
        {
            get { return this.lanIPField; }
            set { this.lanIPField = value; }
        }

        /// <remarks/>
        public string lanMAC
        {
            get { return this.lanMACField; }
            set { this.lanMACField = value; }
        }

        /// <remarks/>
        public string lanMASK
        {
            get { return this.lanMASKField; }
            set { this.lanMASKField = value; }
        }

        /// <remarks/>
        public string lanGW
        {
            get { return this.lanGWField; }
            set { this.lanGWField = value; }
        }

        /// <remarks/>
        public string lanDNS1
        {
            get { return this.lanDNS1Field; }
            set { this.lanDNS1Field = value; }
        }

        /// <remarks/>
        public string lanDNS2
        {
            get { return this.lanDNS2Field; }
            set { this.lanDNS2Field = value; }
        }

        /// <remarks/>
        public string statLan
        {
            get { return this.statLanField; }
            set { this.statLanField = value; }
        }

        /// <remarks/>
        public string nBat
        {
            get { return this.nBatField; }
            set { this.nBatField = value; }
        }

        /// <remarks/>
        public string mtTotal
        {
            get { return this.mtTotalField; }
            set { this.mtTotalField = value; }
        }

        /// <remarks/>
        public string mtUsada
        {
            get { return this.mtUsadaField; }
            set { this.mtUsadaField = value; }
        }

        /// <remarks/>
        public string datahora
        {
            get { return this.datahoraField; }
            set { this.datahoraField = value; }
        }

        /// <remarks/>
        public string verSoft
        {
            get { return this.verSoftField; }
            set { this.verSoftField = value; }
        }

        /// <remarks/>
        public string verLay
        {
            get { return this.verLayField; }
            set { this.verLayField = value; }
        }

        /// <remarks/>
        public string ultimoCFe
        {
            get { return this.ultimoCFeField; }
            set { this.ultimoCFeField = value; }
        }

        /// <remarks/>
        public string listaInicial
        {
            get { return this.listaInicialField; }
            set { this.listaInicialField = value; }
        }

        /// <remarks/>
        public string listafinal
        {
            get { return this.listafinalField; }
            set { this.listafinalField = value; }
        }

        /// <remarks/>
        public string dhTransmissao
        {
            get { return this.dhTransmissaoField; }
            set { this.dhTransmissaoField = value; }
        }

        /// <remarks/>
        public string dhComunicacao
        {
            get { return this.dhComunicacaoField; }
            set { this.dhComunicacaoField = value; }
        }

        /// <remarks/>
        public string CERT_EMISSAO
        {
            get { return this.cERT_EMISSAOField; }
            set { this.cERT_EMISSAOField = value; }
        }

        /// <remarks/>
        public string CERT_VENCIMENTO
        {
            get { return this.cERT_VENCIMENTOField; }
            set { this.cERT_VENCIMENTOField = value; }
        }

        /// <remarks/>
        public string ESTADO_OPERACAO
        {
            get { return this.eSTADO_OPERACAOField; }
            set { this.eSTADO_OPERACAOField = value; }
        }
    }

}