//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class consCmd {
    
    private consCmdTpAmb tpAmbField;
    
    private string cUFField;
    
    private string xServField;
    
    private consCmdComando comandoField;
    
    private string nSegField;
    
    private string dhEnvioField;
    
    private string nserieSATField;
    
    private decimal versaoField;
    
    /// <remarks/>
    public consCmdTpAmb tpAmb {
        get {
            return this.tpAmbField;
        }
        set {
            this.tpAmbField = value;
        }
    }
    
    /// <remarks/>
    public string cUF {
        get {
            return this.cUFField;
        }
        set {
            this.cUFField = value;
        }
    }
    
    /// <remarks/>
    public string xServ {
        get {
            return this.xServField;
        }
        set {
            this.xServField = value;
        }
    }
    
    /// <remarks/>
    public consCmdComando comando {
        get {
            return this.comandoField;
        }
        set {
            this.comandoField = value;
        }
    }
    
    /// <remarks/>
    public string nSeg {
        get {
            return this.nSegField;
        }
        set {
            this.nSegField = value;
        }
    }
    
    /// <remarks/>
    public string dhEnvio {
        get {
            return this.dhEnvioField;
        }
        set {
            this.dhEnvioField = value;
        }
    }
    
    /// <remarks/>
    public string nserieSAT {
        get {
            return this.nserieSATField;
        }
        set {
            this.nserieSATField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal versao {
        get {
            return this.versaoField;
        }
        set {
            this.versaoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum consCmdTpAmb {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class consCmdComando {
    
    private string[] statusField;
    
    private string idCmdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("status")]
    public string[] status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idCmd {
        get {
            return this.idCmdField;
        }
        set {
            this.idCmdField = value;
        }
    }
}
