//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDV_ORCAMENTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Auditoria {
            get {
                return ((int)(this["Auditoria"]));
            }
            set {
                this["Auditoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("initial catalog=M:\\TRILHEIROS\\D - Bases de Clientes\\Samuca\\CLIPP.FDB;data source=" +
            "localhost;user id=SYSDBA;Password=masterkey;charset=WIN1252")]
        public string NetworkDB {
            get {
                return ((string)(this["NetworkDB"]));
            }
            set {
                this["NetworkDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ambi Orçamento")]
        public string NomeSoftware {
            get {
                return ((string)(this["NomeSoftware"]));
            }
            set {
                this["NomeSoftware"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("initial catalog=M:\\TRILHEIROS\\D - Bases de Clientes\\Samuca\\CLIPP.FDB;data source=" +
            "localhost;user id=SYSDBA;Password=masterkey;charset=WIN1252")]
        public string FDBOrcaConnString {
            get {
                return ((string)(this["FDBOrcaConnString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CutePDF Writer")]
        public string ImpressoraUSB {
            get {
                return ((string)(this["ImpressoraUSB"]));
            }
            set {
                this["ImpressoraUSB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mensagem de Rodapé")]
        public string rodape {
            get {
                return ((string)(this["rodape"]));
            }
            set {
                this["rodape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConfigSensivelVersaoAlterada {
            get {
                return ((bool)(this["ConfigSensivelVersaoAlterada"]));
            }
            set {
                this["ConfigSensivelVersaoAlterada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int no_caixa {
            get {
                return ((int)(this["no_caixa"]));
            }
            set {
                this["no_caixa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TipoImpressora {
            get {
                return ((int)(this["TipoImpressora"]));
            }
            set {
                this["TipoImpressora"] = value;
            }
        }
    }
}
